=== logimic/gateway-dashboard/src/assets/cfg/JsonSchema/dashboardConfig-schema-1-0-0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "http://example.com/example.json",
    "self": {
        "vendor": "com.logimic",
        "name": "serverConfig",
        "format": "jsonschema",
        "version": "1-0-0"
    },
    "type": "object",
    "properties": {
        "numberColumns": {
            "type": "integer",
            "description": "Number of tiles columns.",
            "default": 5
        },
        "numberRows": {
            "type": "integer",
            "description": "Number of tiles rows.",
            "default": 5
        },
        "initSkin": {
            "type": "string",
            "description": "One of predefined skins...",
            "default": "Male",
            "enum": [
                "Male",
                "Female"
            ]
        },
        "timeTile": {
            "type": "boolean",
            "description": "Enable/disable display of time tile.",
            "default": true
        },
        "facerecogTile": {
            "type": "boolean",
            "description": "Enable/disable display face recognition tile.",
            "default": false
        },
        "enableLogo": {
            "type": "integer",
            "description": "Number of enabled logos",
            "default": 2
        },
        "disableNames": {
            "type": "array",
            "items": {
                "type": "string",
                "description": "Name of thing.",
                "default": "bla"
            }
        },
        "disableAtypes": {
            "type": "array",
            "items": {
                "type": "string",
                "description": "Atype of thing.",
                "default": "Temperature"
            }
        }
    }
}

=== logimic/gateway-dashboard/src/assets/cfg/dashboardConfig___Aaeon.json
{
    "numberColumns":5,
    "numberRows":5,
    "initSkin": "Male",
    "timeTile": true,
    "enableLogo": 2,
    "disableNames": [
      "faceRecog",
      "cooper/Extra-low_voltage",
      "up2/ledg",
      "up2/ledr"
    ],
    "disableAtypes": [
      "Acceleration",
      "BinaryData",
      "Time",
      "Frequency",
      "Power",
      "PowerFactor",
      "Undef",
      "Consumption",
      "DateTime"
    ]
}
